### ISSUE TITLE
Query command always returns no result

### ISSUE THREAD

**Issue by metaturso** [jorissteyn/phptags#5]
I have indexed the PHPTags codebase with `bin/phptags --root src`.

The database file is generated correctly and I can query it directly using sqlite. The data seem to be all there.

When searching for the definition or the references of a random class using the `query` argument, the program ends without any output but a newline, e.g.

``` sh
> bin/phptags query InterfaceDefinition

>
```

I didn't have enough time to look around the code to find the problem and fix it, and to be frank I don't even know if this is a problem or a case of PEBKAC.

**Comment by jorissteyn** [comment]
Not PEBKAC, just rushed documentation :). The example "phptags query ^FindThis$" was wrong because the "^" was implicit; it was always prepended to the query so you'd have to query for "PhpTags\IndexCommand" or ".*IndexCommand" to get the results you're looking for.

I found some more bugs in phptags and edep-master so I took the chance to change how this works. From 0.0.3 on "phptags query" matches the tag name anywhere, not necessarily from the start. That means if you want to query the fully qualified name, you have to prepend "^" to the query.

Make sure you update both repos in order to keep the edep-jump/ia-fast-jump working.
